spring:
  application:
    name: iemp-encapsulation-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/    
      
server:
  context-path: /iempEncapsulation
  port: 8080



