spring:
  application:
    name: data-association-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/    
server:
  context-path: /dataAssociation
  port: 8080



